//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMathSheets.CommonLib.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsgResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMathSheets.CommonLib.Properties.MsgResources", typeof(MsgResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   E0001L:指定的信息與ExportAttribute不一致或者發現多個 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0001L {
            get {
                return ResourceManager.GetString("E0001L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0001L:指定運算符實例準備作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0001L {
            get {
                return ResourceManager.GetString("I0001L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0002L:{0}運算符實例作成完畢 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0002L {
            get {
                return ResourceManager.GetString("I0002L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0003L:MEF容器中已經收集到指定類型的運算符類型并準備實例化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0003L {
            get {
                return ResourceManager.GetString("I0003L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0004L:MEF容器中已經收集到指定類型的運算符類型所需的參數類型并準備實例化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0004L {
            get {
                return ResourceManager.GetString("I0004L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0005L:指定ID【{0}】參數實例初期化完成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0005L {
            get {
                return ResourceManager.GetString("I0005L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0006L:指定類型的運算符計算式開始構築 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0006L {
            get {
                return ResourceManager.GetString("I0006L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0007L:指定類型的運算符計算式構築完畢 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0007L {
            get {
                return ResourceManager.GetString("I0007L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0008L:MEF容器中已經收集到指定類型的HTML支援類類型并準備實例化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0008L {
            get {
                return ResourceManager.GetString("I0008L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0009L:指定類型的HTML支援類開始繪製HTML に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0009L {
            get {
                return ResourceManager.GetString("I0009L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0010L:指定類型的支援類HTML繪製完畢 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0010L {
            get {
                return ResourceManager.GetString("I0010L", resourceCulture);
            }
        }
    }
}
