//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMathSheets.CommonLib.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsgResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMathSheets.CommonLib.Properties.MsgResources", typeof(MsgResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   E0001L:指定的信息與ExportAttribute不一致或者發現多個 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0001L {
            get {
                return ResourceManager.GetString("E0001L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0018L:指定的{0}題型策略對象未找到 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0018L {
            get {
                return ResourceManager.GetString("E0018L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0019L:指定的{0}題型參數對象未找到 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0019L {
            get {
                return ResourceManager.GetString("E0019L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0020L:指定的{0}計算式對象未找到 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0020L {
            get {
                return ResourceManager.GetString("E0020L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0021L:指定的{0}題型HTML支援類對象未找到 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0021L {
            get {
                return ResourceManager.GetString("E0021L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0022L:指定的{0}題型HTML替換標籤未找到 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0022L {
            get {
                return ResourceManager.GetString("E0022L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0023L:計算式對象沒有實例化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0023L {
            get {
                return ResourceManager.GetString("E0023L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0024L:指定的運算符參數{0}不正確 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0024L {
            get {
                return ResourceManager.GetString("E0024L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0025L:小時數或者分鐘數未指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0025L {
            get {
                return ResourceManager.GetString("E0025L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0026L:指定小時數{0}越界 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0026L {
            get {
                return ResourceManager.GetString("E0026L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0027L:指定{0}文件的MathSheetMarker屬性未定義 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0027L {
            get {
                return ResourceManager.GetString("E0027L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0036L:指定參數【{0}】的值為NULL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0036L {
            get {
                return ResourceManager.GetString("E0036L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0037L:指定對象為NULL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0037L {
            get {
                return ResourceManager.GetString("E0037L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E0038L:未定義的日誌類型 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0038L {
            get {
                return ResourceManager.GetString("E0038L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0001L:指定運算符實例準備作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0001L {
            get {
                return ResourceManager.GetString("I0001L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0002L:{0}運算符實例作成完畢 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0002L {
            get {
                return ResourceManager.GetString("I0002L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0003L:MEF容器中已經收集到指定類型的運算符類型并準備實例化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0003L {
            get {
                return ResourceManager.GetString("I0003L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0004L:MEF容器中已經收集到指定類型的運算符類型所需的參數類型并準備實例化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0004L {
            get {
                return ResourceManager.GetString("I0004L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0005L:指定ID【{0}】參數實例初期化完成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0005L {
            get {
                return ResourceManager.GetString("I0005L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0006L:指定類型的運算符計算式開始構築 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0006L {
            get {
                return ResourceManager.GetString("I0006L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0007L:指定類型的運算符計算式構築完畢 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0007L {
            get {
                return ResourceManager.GetString("I0007L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0008L:MEF容器中已經收集到指定類型的HTML支援類類型并準備實例化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0008L {
            get {
                return ResourceManager.GetString("I0008L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0009L:指定類型的HTML支援類開始繪製HTML に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0009L {
            get {
                return ResourceManager.GetString("I0009L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0010L:指定類型的支援類HTML繪製完畢 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0010L {
            get {
                return ResourceManager.GetString("I0010L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0011L:題型HTML支援類spring對象工廠配置導入操作已經完成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0011L {
            get {
                return ResourceManager.GetString("I0011L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0012L:{0}題型的HTML支援類對象注入準備 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0012L {
            get {
                return ResourceManager.GetString("I0012L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0013L:{0}題型的HTML支援類對象實例化完成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0013L {
            get {
                return ResourceManager.GetString("I0013L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0014L:指定題型的HTML模板作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0014L {
            get {
                return ResourceManager.GetString("I0014L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0015L:替換HTML模板中{0}的注入點信息 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0015L {
            get {
                return ResourceManager.GetString("I0015L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0016L:{0}題型HTML模板注入開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0016L {
            get {
                return ResourceManager.GetString("I0016L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0017L:靜態HTML文件作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0017L {
            get {
                return ResourceManager.GetString("I0017L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0028L:指定{0}文件被讀取加載 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0028L {
            get {
                return ResourceManager.GetString("I0028L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0029L:模塊識別信息（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0029L {
            get {
                return ResourceManager.GetString("I0029L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0030L:模塊讀取處理完畢（共計：{0}個） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0030L {
            get {
                return ResourceManager.GetString("I0030L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0031L:模塊讀取處理開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0031L {
            get {
                return ResourceManager.GetString("I0031L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0032L:指定題型編號為空，默認使用{0}作為題型編號 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0032L {
            get {
                return ResourceManager.GetString("I0032L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0033L:指定題型編號{0}不存在，默認使用{1}作為題型編號 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0033L {
            get {
                return ResourceManager.GetString("I0033L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0034L:指定ID【{0}】計算式作成處理開始，以下計算式列舉： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0034L {
            get {
                return ResourceManager.GetString("I0034L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0035L:指定ID【{0}】計算式作成處理結束 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0035L {
            get {
                return ResourceManager.GetString("I0035L", resourceCulture);
            }
        }
    }
}
