//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMathSheets.MathSheetsSettingApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsgResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMathSheets.MathSheetsSettingApp.Properties.MsgResources", typeof(MsgResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   E0001A:系統異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E0001A {
            get {
                return ResourceManager.GetString("E0001A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0001A:畫面初期化開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0001A {
            get {
                return ResourceManager.GetString("I0001A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0002A:開始出題 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0002A {
            get {
                return ResourceManager.GetString("I0002A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0003A:{0}題型HTML模板注入開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0003A {
            get {
                return ResourceManager.GetString("I0003A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0004A:替換HTML模板中{0}的注入點信息 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0004A {
            get {
                return ResourceManager.GetString("I0004A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0005A:靜態HTML文件作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0005A {
            get {
                return ResourceManager.GetString("I0005A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0006A:{0}題型選擇 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0006A {
            get {
                return ResourceManager.GetString("I0006A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0007A:{0}題型移除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0007A {
            get {
                return ResourceManager.GetString("I0007A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0008A:畫面初期化處理完畢 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0008A {
            get {
                return ResourceManager.GetString("I0008A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0009A:題型未選擇 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0009A {
            get {
                return ResourceManager.GetString("I0009A", resourceCulture);
            }
        }
    }
}
