//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMathSheets.TheFormulaShows.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsgResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMathSheets.TheFormulaShows.Properties.MsgResources", typeof(MsgResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   I0001F:題型HTML支援類spring對象工廠配置導入操作已經完成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0001F {
            get {
                return ResourceManager.GetString("I0001F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0002F:{0}題型的HTML支援類對象注入準備 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0002F {
            get {
                return ResourceManager.GetString("I0002F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0003F:{0}題型的HTML支援類對象實例化完成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0003F {
            get {
                return ResourceManager.GetString("I0003F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I0004F:指定題型的HTML模板作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string I0004F {
            get {
                return ResourceManager.GetString("I0004F", resourceCulture);
            }
        }
    }
}
