name: do build MyMathSheets
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  WORKING_DIR: w_${{ github.run_id }}
  target_Solution: "MyMathSheets.sln"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
          path: ${{ env.WORKING_DIR }}
    - name: checkout lfs contens
      run: |
          git lfs checkout
          git lfs pull
      working-directory: ${{ env.WORKING_DIR }}

    - name: setup .NET and install SDK
      uses: actions/setup-dotnet@v3
      id: install_dotnet
      with:
          dotnet-version: '5.0.x'
          
    - run: echo '${{ steps.install_dotnet.outputs.dotnet-version }}'

    - name: dotnet build 
      id: dotnet_build
      run: msbuild /p:Configuration=Debug ./${{ env.target_Solution }}
