name: do build MyMathSheets
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  WORKING_DIR: w_${{ github.run_id }}
  target_Solution: "MyMathSheets.sln"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
          path: ${{ env.WORKING_DIR }}
          
    - name: checkout lfs contens
      run: |
          git lfs checkout
          git lfs pull
      working-directory: ${{ env.WORKING_DIR }}

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
          msbuild-architecture: x64
          
    - name: Build app for release
      run: msbuild CommonLib\MyMathSheets.CommonLib.csproj -t:rebuild -verbosity:diag -property:Configuration=Debug
