# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: MyMathSheets_test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

env:
  OUTPUT_DIR: C:/runner/output/${{ github.run_id }}/tests
  # Path to the solution file relative to the root of the project.
  WORKING_DIR: w_${{ github.run_id }}

  # Configuration type to build.
  BUILD_CONFIGURATION: Debug
  
jobs:
  test:

    runs-on: windows-latest

    steps:
    - name: CheckOut Repository
      uses: actions/checkout@v3
      with:
        path: ${{ env.WORKING_DIR }}

    - name: checkout lfs contens
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        git lfs checkout
        git lfs pull
        
    - name: Restore NuGet packages
      working-directory: ${{ env.WORKING_DIR }}
      run: nuget restore MyMathSheets.All.sln

    - name: Setup .NET    
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      working-directory: ${{ env.WORKING_DIR }}
      run: dotnet restore MyMathSheets.CommonLibTest.csproj
      
    - name: Test
      working-directory: ${{ env.WORKING_DIR }}
      run: dotnet test MyMathSheets.CommonLibTest.csproj
      # dotnet test --no-build --verbosity normal

