# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MyMathSheet_MSBuild

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ${{ env.GITHUB_WORKSPACE }}

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  pre_process:
    runs-on: windows-latest
    steps:
    - name: CheckOut Repository
      uses: actions/checkout@v3
        
    - name: checkout lfs contens
      run: |
        git lfs checkout
        git lfs pull

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: nuget restore MyMathSheets.All.sln

  build_common:
    needs: pre_process
    runs-on: windows-latest
    steps:
    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} MyMathSheets.Common.sln /t:rebuild /v:Normal
        if (-Not $?) {
          exit 1
        } else {
          exit 0
        }

  build_strategy:
    needs: build_common
    runs-on: windows-latest
    steps:
    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}  
      run: |
        $targetSolution = "MyMathSheets.Strategy.sln"
        msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} .\$targetSolution /t:rebuild /v:Normal
        if (-Not $?) {
          exit 1
        } else {
          exit 0
        }

  build_shows:
    needs: build_strategy
    runs-on: windows-latest
    steps:
    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        $targetSolution = "MyMathSheets.Shows.sln"
        msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} .\$targetSolution /t:rebuild /v:Normal
        if (-Not $?) {
          exit 1
        } else {
          exit 0
        }
